TrajectoryPlannerROS:

  holonomic_robot: false
  controller_frequency: 10.0

  #min_vel_x: 0.15
  #min_in_place_vel_theta: 0.3
  #escape_vel: -0.25

  #xy_goal_tolerance: 0.15
  #yaw_goal_tolerance: 0.05

  max_vel_x: 0.45 #RobotSetup
  min_vel_x: 0.1  #RobotSetup
  max_vel_theta: 1.0 #RobotSetup
  min_in_place_vel_theta: 0.4 #RobotSetup

  #acc_lim_theta: 3.2 #RobotSetup
  #acc_lim_x: 2.5 #RobotSetup
  #acc_lim_y: 2.5 #RobotSetup

  # Goal Tolerance Parameters
  xy_goal_tolerance: 0.15  #bex
  yaw_goal_tolerance: 0.05  #bex
