local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 1.0  #bex 5.0, was 1.0
   publish_frequency: 1.0 #bex 5.0, was 1.0
   width: 5.0  #bex 5.0, was 20.0 -> 5.0    #robot keep on circling with 8.0
   height: 5.0 #bex 5.0, was 20.0 -> 5.0    #robot keeep on circling with 8.0
   resolution: 0.05
   static_map: false  #was false -> true -> false
   rolling_window: true #was true -> false -> true
